server:
  port: 8080

spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:templates/, classpath:static/


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package:  com.lxq.upload.module.entity
